name: Run Python Script on README.md Changes

# 定义触发条件：仅当 README.md 文件被推送修改时触发
on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  check-websites:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run script
      run: python webtest.py
